apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-deliveryservice
  labels:
    app: atlas-deliveryservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atlas-deliveryservice
  template:
    metadata:
      labels:
        app: atlas-deliveryservice
    spec:
      containers:
      - name: atlas-deliveryservice
        image: atlas-deliveryservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-deliveryservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: atlas-deliveryservice