apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowmanmaterialsupplier-microservice
  labels:
    app: snowmanmaterialsupplier-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowmanmaterialsupplier-microservice
  template:
    metadata:
      labels:
        app: snowmanmaterialsupplier-microservice
    spec:
      containers:
      - name: snowmanmaterialsupplier-microservice
        image: docker.io/p97akita/snowmanmaterialsupplier-microservice:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snowmanmaterialsupplier-microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    app: snowmanmaterialsupplier-microservice