apiVersion: apps/v1
kind: Deployment
metadata:
  name: cactusbuilder-microservice
  labels:
    app: cactusbuilder-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cactusbuilder-microservice
  template:
    metadata:
      labels:
        app: cactusbuilder-microservice
    spec:
      containers:
      - name: cactusbuilder-microservice
        image: docker.io/p97akita/cactusbuilder-microservice:v0.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cactusbuilder-microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    app: cactusbuilder-microservice