#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build
WORKDIR /src
COPY ["Display.Microservice/Display.Microservice.csproj", "Display.Microservice/"]
RUN dotnet restore "Display.Microservice/Display.Microservice.csproj"
COPY . .
WORKDIR "/src/Display.Microservice"
RUN dotnet build "Display.Microservice.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Display.Microservice.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Display.Microservice.dll"]