apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-phoenix
  labels:
    app: atlas-phoenix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atlas-phoenix
  template:
    metadata:
      labels:
        app: atlas-phoenix
    spec:
      containers:
      - name: atlas-phoenix
        image: docker.io/p97akita/atlas-phoenix:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-phoenix
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32100
  selector:
    app: atlas-phoenix