#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch AS build
WORKDIR /src
COPY ["SnowmanBuilder.Microservice/SnowmanBuilder.Microservice.csproj", "SnowmanBuilder.Microservice/"]
RUN dotnet restore "SnowmanBuilder.Microservice/SnowmanBuilder.Microservice.csproj"
COPY . .
WORKDIR "/src/SnowmanBuilder.Microservice"
RUN dotnet build "SnowmanBuilder.Microservice.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SnowmanBuilder.Microservice.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SnowmanBuilder.Microservice.dll"]