apiVersion: apps/v1
kind: Deployment
metadata:
  name: cactusbuilder
  labels:
    app: cactusbuilder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cactusbuilder
  template:
    metadata:
      labels:
        app: cactusbuilder
    spec:
      containers:
      - name: cactusbuilder
        image: docker.io/p97akita/cactusbuilder:v0.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cactusbuilder
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: cactusbuilder