apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowmanbuilder
  labels:
    app: snowmanbuilder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snowmanbuilder
  template:
    metadata:
      labels:
        app: snowmanbuilder
    spec:
      containers:
      - name: snowmanbuilder
        image: snowmanbuilder
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snowmanbuilder
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31002
  selector:
    app: snowmanbuilder