version: '3.4'

services:
  display:
    image: ${DOCKER_REGISTRY-}display
    build:
      context: ..
      dockerfile: P97.Display.Microservice/Containers/Dockerfile_Linux
    ports:
      - 30000:80
      
  warehouse:
    image: ${DOCKER_REGISTRY-}warehouse
    build:
      context: ..
      dockerfile: P97.Warehouse.Microservice/Containers/Dockerfile_Linux
    ports:
      - 30001:80
      
  cactusbuilder:
    image: ${DOCKER_REGISTRY-}cactusbuilder
    build:
      context: ..
      dockerfile: P97.CactusBuilder.Microservice/Containers/Dockerfile_Linux
    ports:
      - 31000:80
      
  cactusmaterialsupplier:
    image: ${DOCKER_REGISTRY-}cactusmaterialsupplier
    build:
      context: ..
      dockerfile: P97.CactusMaterialSupplier.Microservice/Containers/Dockerfile_Linux
    ports:
      - 31001:80
      
  snowmanbuilder:
    image: ${DOCKER_REGISTRY-}snowmanbuilder
    build:
      context: ..
      dockerfile: P97.SnowmanBuilder.Microservice/Containers/Dockerfile_Linux
    ports:
      - 31002:80
  
  snowmanmaterialsupplier:
    image: ${DOCKER_REGISTRY-}snowmanmaterialsupplier
    build:
      context: ..
      dockerfile: P97.SnowmanMaterialSupplier.Microservice/Containers/Dockerfile_Linux
    ports:
      - 31003:80
      
  atlas-deliveryservice:
    image: ${DOCKER_REGISTRY-}atlas-deliveryservice
    build:
      context: ..
      dockerfile: P97.Atlas.Federation.DeliveryService.Microservice/Containers/Dockerfile_Linux
    ports:
      - 32000:80
      
  atlas-phoenix:
    image: ${DOCKER_REGISTRY-}atlas-phoenix
    build:
      context: ..
      dockerfile: P97.Atlas.States.Phoenix.Microservice/Containers/Dockerfile_Linux
    ports:
      - 32100:80
      
  atlas-sapporo:
    image: ${DOCKER_REGISTRY-}atlas-sapporo
    build:
      context: ..
      dockerfile: P97.Atlas.States.Sapporo.Microservice/Containers/Dockerfile_Linux
    ports:
      - 32101:80